### ISSUE TITLE
If users' upn does not have user@contonso.onmicrosoft.com login fails

### ISSUE THREAD

**Issue by yaserMow89** [himmelblau-idm/himmelblau#552]
**Description**
We have a test environment and everything works fine there, but in the production environment it does not work. The difference is that in the test environment our users' upns are user@org.onmicrosoft.com, but in the production environment our users' upns are user@org.domain.com. 

**Steps to Reproduce**
1. If I set the `domains = org.onmicrosoft.com` and the `pam_allow_groups=user@org.onmicrosoft.com`, then for `getent passwd user@org.onmicrosoft.com` I get nothing, and trying to login using `su -l user@org.onmicrosoft.com` I get the `su: user user@org.onmicrosoft.com does not exist or the user entry does not contain all the required fields`.
2. If I try to setup `domains = ads.org.com` and the `pam_allow_groups=user@org.onmicrosoft.com` then trying to login with `su -l user@ads.org.com` I get `No push? Check your mobile device's internet connection.
General failure: {"AuthorizationState":3}` 
3. If I try to setup `domains = ads.org.com` and the `pam_allow_group=user@ads.org.com` which is the real UPN for the user, I again get the error: `No push? Check your mobile device's internet connection.
General failure: {"AuthorizationState":3}` 

**Logs and Output**
Attaching the logs outputs for both files here, please keep in mind that the logs with orgdevelopment is on the test environment

[himmelblau.txt](https://github.com/user-attachments/files/20576552/himmelblau.txt)
[himmelblau-tasks.txt](https://github.com/user-attachments/files/20576551/himmelblau-tasks.txt)

**Environment**
- **Ubuntu 24.04**: 
- **github release**: 
- **0.9.14**: 

---

### 💡 Help Make It Happen!
Want to see this bug fixed faster? Fund its implementation through our **Backer's Bounty** program, where you choose which bug fixes get priority!

[![Donate to Our Collective](https://opencollective.com/himmelblau/donate/button.png?color=blue)](https://himmelblau-idm.org/backers.html#backers-bounty)

Your support helps drive Himmelblau’s evolution!

**Comment by dmulder** [comment]
>     1. If I set the `domains = org.onmicrosoft.com` and the `pam_allow_groups=user@org.onmicrosoft.com`, then for `getent passwd user@org.onmicrosoft.com` I get nothing, and trying to login using `su -l user@org.onmicrosoft.com` I get the `su: user user@org.onmicrosoft.com does not exist or the user entry does not contain all the required fields`.

The debug shows that it can't resolve that domain name. Try manually resolving the name and send me the results:

`curl -H 'accept: */*' 'https://odc.officeapps.live.com/odc/v2.1/federationProvider?domain=himmelblau-idm.org'`

Replace `himmelblau-idm.org` with your own domain name.

>     2. If I try to setup `domains = ads.org.com` and the `pam_allow_groups=user@org.onmicrosoft.com` then trying to login with `su -l user@ads.org.com` I get `No push? Check your mobile device's internet connection. General failure: {"AuthorizationState":3}`
> 
>     3. If I try to setup `domains = ads.org.com` and the `pam_allow_group=user@ads.org.com` which is the real UPN for the user, I again get the error: `No push? Check your mobile device's internet connection. General failure: {"AuthorizationState":3}`
> 

Are you getting a push notification from MS Authenticator on your device? I don't recall what `AuthorizationState == 3` means. I think it means you dismissed the notification? You should be getting a prompt indicating an entropy code as well. Are you not getting that? If so, then this is a bug. I saw a similar issue on SLES 16.0 beta. For some reason that second prompt appears to be clobbering the initial entropy code prompt.

**Comment by yaserMow89** [comment]
Hey,
Here is the output for the domain resolving

```bash
{"environment":"Global","endpoint":[{"type":"MSA","authentication_endpoint":"https://login.live.com/oauth20_authorize.srf","token_endpoint":"https://login.live.com/oauth20_token.srf"},{"type":"OrgId","authentication_endpoint":"https://login.microsoftonline.com/common/oauth2/authorize","token_endpoint":"https://login.microsoftonline.com/common/oauth2/token"}],"tenantId":"orgTenantID","authority_host":"login.microsoftonline.com","graph":"https://graph.microsoft.com"}
```

No, we are getting no push notifications on our devices.

**Comment by yaserMow89** [comment]
We just changed a test user upn to user@org.onmicrosoft.com manually, and it is working, but it won't be very useful if it is like this because, we can't make this change to every user.

**Comment by dmulder** [comment]
This should be resolved by 5763d80b4faca19eca4ea7893dd468a31bdf3ed7.

**Comment by yaserMow89** [comment]
Hi @dmulder, 
we are still having this issue. I installed the latest version and changed the config file to different scenarios, so we can login, but we are getting `Authentication failure` on the terminal and `Sorry password authentication did not work, please try again` 
- config file is: 
```
[global]
domains = ORG.onmicrosoft.com
pam_allow_groups = USER@ads.ORG.com
id_attr_map = name
home_attr = CN
home_alias = CN
use_etc_skel = true


app_id = APP_ID


id_attr_map = rfc2307
rfc2307_group_fallback_map = name

debug = true
```

Log files are both attached below

[himmelblau.log](https://github.com/user-attachments/files/21830268/himmelblau.log)
[himmelblau-tasks.log](https://github.com/user-attachments/files/21830267/himmelblau-tasks.log)

**Environment**
- Ubuntu 22.04
- Package source --> [web page](https://himmelblau-idm.org/downloads/index.html)
- version `1.0.0-beta2`

**Comment by dmulder** [comment]
I'll reopen this to investigate. Could you also try the latest version of himmelblau (1.2.1)?

**Comment by yaserMow89** [comment]
The issue is closed, since it was fixed with version 1.2.1
