### ISSUE TITLE
NixOS user not listed on GNOME

### ISSUE THREAD

**Issue by Srylax** [himmelblau-idm/himmelblau#739]
**Description**
When using the NixOS module the user does not get listed once logged in. This degrades UX because now the user need to enter the username as well. Also the user profile image does not get written.

Additional but unrelated to gnome the o365 and Firefox extensions to not get loaded.  Would it be possible to provide further nix options to configure them?

**Logs and Output**
```
[error]: Failed creating file for user profile photo: 0s { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
[error]: Failed creating file for user profile settings: 0s { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
```

**Configuration**
```nix
services.himmelblau = {
    enable = true;
    settings = {
      enable_hello = false;
      domains = ["**"];
      home_alias = "CN";
    };
  };
```

**Environment**
- **Linux Distro**: NixOS
- **Package source (distro package/github release/self built)**: Nix Flake
- **Himmelblau Version**:  2.0.0/master

---

### 💡 Help Make It Happen!
Want to see this bug fixed faster? Fund its implementation through our **Backer's Bounty** program, where you choose which bug fixes get priority!

[![Donate to Our Collective](https://opencollective.com/himmelblau/donate/button.png?color=blue)](https://himmelblau-idm.org/backers.html#backers-bounty)

For US tax exempt donations:

[![Donate US Tax Exempt](https://www.spi-inc.org/images/paypal_btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8GYKFLX9UNCH2)

Your support helps drive Himmelblau’s evolution!

**Comment by dmulder** [comment]
Someone from the Nix community will need to volunteer to add the options. Perhaps @iLikeToCode can try?

In regards to the GNOME issues, I'd guess the `himmelblaud-tasks` sections needs fixed in the [`flake.nix`](https://github.com/himmelblau-idm/himmelblau/blob/main/flake.nix) file to update `ReadWritePaths` to look like we've done for the systemd file at [`himmelblaud-tasks.service`](https://github.com/himmelblau-idm/himmelblau/blob/main/platform/debian/himmelblaud-tasks.service).

**Comment by Srylax** [comment]
I tried adding `/var/lib` to `ReadWritePaths` this resolved the `ReadOnlyFilesystem` error message but now i get:
```
[error]: Failed fetching user profile photo: GeneralFailure("federation provider not set")
```
The user is still not shown on Gnome

update: the file does get written correctly with the new `/var/lib` permission and shows up when logging out.
HOWEVER once I restart the device all files in `/var/lib/AccountServices/users` gets deleted

~~On another note, group member ship do not work:~~

```nix
local_groups = [ "systemd-journal" ];
```
~~results in:~~
```
[error]: Failed adding user to local group systemd-journal
```
~~should I open a new bug report?~~
